---
- hosts: hosts
  tasks:
  - name: "Destroy EC2"
    terraform:
      project_path: /opt/terraform
      binary_path: /opt/terraform/terraform
      variables:
        region: us-west-1
      state: absent
