---
- hosts: hosts
  vars:
    workspace: "{{ lookup('env','workspace') }}"
  tasks:
  - name: "Plan EC2"
    terraform:
      project_path: '{{ workspace }}/tf_scripts/'
      binary_path: '{{ workspace }}/tf_scripts/terraform'
      plan_file: '{{ workspace }}/tf_scripts/ec2.plan'
      state: planned
