---
- hosts: hosts
  tasks:
  - name: "Plan EC2"
    terraform:
      project_path: 'tf_scripts/'
      binary_path: 'tf_scripts/terraform'
      plan_file: 'tf_scripts/ec2.plan'
      state: planned
